#!/bin/bash
pacman -S xorg xorg-xinit

pacman -S plasma-desktop

pacman -S sddm

pacman -S konsole dolphin kate Okular KTorrent Falkon Apper discover
# pacman -S Scribus Konqueror LabPlot Cantor KBibTeX Krita KRDC Krfb Calligra Sheets KTimeTracker firefox KDE Partition Manager

pacman -S powerdevil
pacman -S plasma-pa

# To enable the Breeze theme for SDDM, you need edit SDDM config file. Type in your terminal:
# nano /etc/sddm.conf
# And in the Current theme name, set the theme name to breeze.

pacman -S kdeplasma-addons

pacman -S networkmanager plasma-nm

systemctl stop dhcpcd
systemctl disable dhcpcd

sudo systemctl enable NetworkManager
sudo systemctl start NetworkManager

sudo systemctl enable sddm
sudo systemctl start sddm

# pacman -S openconnect networkmanager-openconnect
